### ISSUE TITLE
bootstrap.R

### ISSUE THREAD

**Issue by petersbr** [pachterlab/sleuth#100]
This is a request for a small api mod.  max_bs seems to be a key parameter for some functions in bootstrap.R.  The default setting limits the results its works with to a maximum of 30 replicates instead of whatever is being supplied in the hd5 file.  I assume it is for computational feasibility, but it is unexpected behavior that isn't noted in the documentation.

My biggest concern is that this behavior isn't clear from the docs.  Noting this since the behavior I was getting out of get_bootstraps() was confusing me until I peeked at the code.

Regards

**Comment by pimentel** [comment]
hi @petersbr 

this is a good point. I'm leaning towards documenting it better, but will think about it for a bit. will definitely go into the next release.

thanks,

harold

**Comment by warrenmcg** [comment]
The documentation for the max_bootstrap has been added, and the default is to now process all available bootstraps. Thus, this issue will now be closed.
