### ISSUE TITLE
Only parallelize when at terminal

### ISSUE THREAD

**Issue by pimentel** [pachterlab/sleuth#101]
Don't parallelize (using `mclapply()`) when in the GUI/RStudio

**Comment by warrenmcg** [comment]
Could I ask what the concern is here? Is it the problem of sending messages back to the main console while using forked processes, or is it the issue that, if the code is taking a while and the user decides to cancel the process, it could freeze RStudio and cause them to lose unsaved edits?

**Comment by warrenmcg** [comment]
On the note of parallelization @pimentel, you may want to consider the work that @petersbr is doing ([most recent commit based on the old code](https://github.com/petersbr/sleuth/commit/228383f7c819976b3c42a8838b9ecdaf77bf615f)), where he is re-implementing the parallelization using the `future` package ([link](https://github.com/HenrikBengtsson/future)). This package was developed by the same person who did `matrixStats`, and is supposed to provide one unified API for using multiple cores or using high-end computer clusters.

**Comment by pimentel** [comment]
hey @warrenmcg ,

I'm pulling from the `mclapply` documentation:

```
It is strongly discouraged to use these functions in GUI or embedded environments, because it leads to several processes sharing the same GUI which will likely cause chaos (and possibly crashes). Child processes should never use on-screen graphics devices.
```

I think it is basically just taking way more memory since it forks the entire process including the GUI stuff.

I will take a look at the suggestions you made and also other possible solutions today/tomorrow.


Thanks,

Harold
