### ISSUE TITLE
what are est_counts

### ISSUE THREAD

**Issue by fruce-ki** [pachterlab/sleuth#104]
Hello!

It is unclear from the documentation what the `est_counts` are. Are they read counts or transcript counts? And what are they normalised for?

Cheers!

**Comment by lakigigar** [comment]
The est_counts are an estimate of the number of counts originating from
each transcript. They are an estimate only because of the assignment of
ambiguously mapping reads. The accuracy of the estimate can be ascertained
via the bootstrap option.

**Comment by fruce-ki** [comment]
Yes but what are they counting? Is it an estimate of the number of reads coming from that transcript type or is it an estimate of the number of copies of that type of transcript? 
Is it based on the TPMs and scaled up for library size? Is it normalised across samples?

**Comment by lakigigar** [comment]
est_counts estimate the number of *reads* coming from each transcript. These are calculated separately for each sample by kallisto. Subsequent normalizations for experiments consisting of multiple samples are performed by sleuth.

**Comment by fruce-ki** [comment]
OK. Thanks!

**Comment by EduEyras** [comment]
Hi, 
what are the normalizations implemented in Sleuth? I could not find a description in the manual or the preprint. Thanks!

**Comment by pimentel** [comment]
Hi @EduEyras,

Currently, we use a DESeq style normalization. Technically any normalization function can be used of the form s_i * x_ij where s_i is the sample normalization constant (known as size factor) and x_ij is the count. The same normalization is used for TPM as well.

To do this, simply supply a different function to `norm_fun_counts` in `sleuth_prep`.

I've been thinking about how to make a more flexible method without being to difficult to use in the standard case. Hopefully for the next version...

Anyway, we will clarify more in the next versions documentation.


Best,

Harold

**Comment by EduEyras** [comment]
Thanks a lot Harold,
Best
Eduardo

Dr. Eyras
ICREA Research Professor
Universitat Pompeu Fabra
Barcelona
Spain
