### ISSUE TITLE
sleuth_prep() Error

### ISSUE THREAD

**Issue by kunstner** [pachterlab/sleuth#111]
Hi,

I'm using sleuth since some time for quantifying differences in gene expression between two conditions. So far, everything was working nicely.

Today, I just re-run sleuth on a dataset I analysed a couple of days ago. Back then, I got no error messages. But today, I got the following error message:

so <- sleuth_prep(s2c, as.formula(model), target_mapping = t2g, min_prop=0.5, aggregation_column ="ens_gene")
reading in kallisto results
dropping unused factor levels
.....normalizing est_counts
17023 targets passed the filter
normalizing tpm
merging in metadata
aggregating by column: ens_gene
Error in `[.data.frame`(target_mapping, , aggregation_column, with = FALSE) : 
  unused argument (with = FALSE)
In addition: Warning message:
In check_target_mapping(tmp_names, target_mapping) :
  intersection between target_id from kallisto runs and the target_mapping is empty. attempted to fix problem by removing .N from target_id, then merging back into target_mapping. please check obj$target_mapping to ensure this new mapping is correct.

I figured out that if I leave out the 'aggregation_column' option, sleuth_prep() runs through without any error. 

I'm running sleuth version 0.29.0 (R 3.4.0) on macOS 10.12.

Any ideas, what could cause the troubles?

Best,
 Axel

**Comment by pimentel** [comment]
Hi Axel,

Is it possible that the annotation and the `target_mapping` you provided might not be compatible:

```
intersection between target_id from kallisto runs and the target_mapping is empty. attempted to fix problem by removing .N from target_id, then merging back into target_mapping. please check obj$target_mapping to ensure this new mapping is correct.
```

?

Which annotation are you using with kallisto and which `target_mapping` are you using? Could you maybe show the first 5 lines of `abundance.tsv` and `head(t2g)`?



Thanks,

Harold

**Comment by BradenPew** [comment]
Hi Axel,

I had the same problem today (`Error in [.data.frame(target_mapping, , aggregation_column, with = FALSE) :
unused argument (with = FALSE)` message stopping the sleuth_prep). I got around it by changing the sleuth_prep gene aggregation function:
`which_agg_id <- unique(mappings[which_tms, ..aggregation_column])`

Hopefully this helps and doesn't mess anything up. Any input on if this is a valid workaround Harold?

Best,

Braden

**Comment by pimentel** [comment]
Hi @BradenPew 

Which annotation and target mapping are you using? I'm trying to reproduce this bug and haven't seen it with the mouse/human annotations I've been testing with.


Thanks,

Harold

**Comment by kunstner** [comment]
Hi Braden,

I'm using mouse data and mapped the data against genome build GRCm38. In R, I just used the common workflow with biomaRt and org.Mm.eg.db to retrieve annotations.

I'm aware of '.N' version number problem for the transcripts. But usually I did not had any troubles with this and the annotation mapping was correct. 

Actually, I was able to analyse the same data set before without any troubles. Just since yesterday, I encounter the problem.

Please find below the first five lines of abundance.tsc and six lines of t2g.

head -n 5 abundance.tsv

target_id	length	eff_length	est_counts	tpm
ENSMUST00000177564.1	16	2.66459	0	0
ENSMUST00000196221.1	9	2.52391	0	0
ENSMUST00000178537.1	12	2.60424	0	0
ENSMUST00000178862.1	14	2.63753	0	0
ENSMUST00000179520.1	11	2.58312	0	0
ENSMUST00000179883.1	16	2.66459	0	0
ENSMUST00000195858.1	10	2.55707	0	0

head(t2g)

                            target_id           ens_gene ext_gene
ENSMUST00000082423 ENSMUST00000082423 ENSMUSG00000064372    mt-Tp
ENSMUST00000082422 ENSMUST00000082422 ENSMUSG00000064371    mt-Tt
ENSMUST00000082421 ENSMUST00000082421 ENSMUSG00000064370  mt-Cytb
ENSMUST00000082420 ENSMUST00000082420 ENSMUSG00000064369    mt-Te
ENSMUST00000082419 ENSMUST00000082419 ENSMUSG00000064368   mt-Nd6
ENSMUST00000082418 ENSMUST00000082418 ENSMUSG00000064367   mt-Nd5

Many thanks,
 Axel

**Comment by pimentel** [comment]
Hey folks,

Thanks for the additional information.

Looking through the code, @BradenPew I believe your fix is probably fine.

I think I fixed it in the more general sense in the `devel` branch. Do you folks mind giving it a shot? Here's how you can install it:

```r
devtools::install_github('pachterlab/sleuth', ref = 'devel')
```

If it works I will merge it into `master` by the end of the week (I'm anticipating more bugs but hoping for none 😄)


Thanks,

Harold

**Comment by kunstner** [comment]
Hi @pimentel,

thank you for providing a the fix. It is working for me as well!

Best,
 Axel

**Comment by warrenmcg** [comment]
Since this was caused by my code and I didn't cover this situation, thanks for the feedback and the fix everyone! @pimentel, I'll look into adding tests to the `testthat` suite to see if we can make sure that this is covered in testing for future changes.

**Comment by procha2** [comment]
I am having the same error during sleuth_prep with the latest sleuth 0.30 and human gencode32 transcriptome when using the gene_mode = T and aggregation_column = ensembl_gene_id
Has this been solved in the past?
