### ISSUE TITLE
x_group not found while running sleuth_wt()

### ISSUE THREAD

**Issue by kunstner** [pachterlab/sleuth#112]
Hi,

I'm using the latest devel version of sleuth 0.29.0. I get an error message while running the Wald test (see below). It seems that during ```sleuth_fit()``` the object ```x_group``` is not added to the sleuth object.

```
> so <- sleuth_prep(
+ 	sample_to_covariates = s2c, 
+ 	full_model = as.formula(model), 
+ 	target_mapping = t2g, min_prop=0.5)
reading in kallisto results
dropping unused factor levels
.....
normalizing est_counts
19862 targets passed the filter
normalizing tpm
merging in metadata
summarizing bootstraps

Warning message:
In check_target_mapping(tmp_names, target_mapping) :
  intersection between target_id from kallisto runs and the target_mapping is empty. attempted to fix problem by removing .N from target_id, then merging back into target_mapping. please check obj$target_mapping to ensure this new mapping is correct.
> 
> so <- sleuth_fit(so, as.formula(model)) # fit full model
fitting measurement error models
shrinkage estimation
computing variance of betas
> so <- sleuth_fit(so, ~1, 'reduced') # fit NULL model
fitting measurement error models
shrinkage estimation
computing variance of betas
> 
> # Make the lrt test
> so <- sleuth_lrt(so, 'reduced', 'full')
> # Make the Wald test
> so <- sleuth_wt(so, which_beta = 'conditionC3H')
Error in eval(x$expr, data, x$env) : object 'x_group' not found
> models(so); tests(so)
[  full  ]
formula:  ~condition 
coefficients:
	(Intercept)
 	conditionC3H
[  reduced  ]
formula:  ~1 
coefficients:
	(Intercept)
~likelihood ratio tests:
	reduced:full

~wald tests:
	no tests found.
```

Many thanks in advance,
 Axel

**Comment by BradenPew** [comment]
Hey Axel,

I got this error message as well after resolving #111, and for now I got around it by reverting the change made in https://github.com/pachterlab/sleuth/pull/106/commits/5fff7b0d2210847bc6d17e1a59ff09faed7349f4.  @pimentel or @warrenmcg will probably have to chime in to see what the best fix is regarding this issue and #102.

Best of luck,

Braden

**Comment by pimentel** [comment]
ah, sorry about that! I just made another push to `devel`. Willing to give it a shot? Let me know.

**Comment by warrenmcg** [comment]
I can confirm that the latest devel commit no longer has this issue (at least with my test samples).

**Comment by kunstner** [comment]
Thanks for fixing the bug. Everything runs smoothly again.

**Comment by dangeles** [comment]
Could I recommend either downgrading current version, patching the current as soon as possible or otherwise sending out a warning to the sleuth user-list? this bug is very easy to encounter, quite difficult to diagnose and will break a large number of scripts unless users download the dev version.

**Comment by pimentel** [comment]
@dangeles thanks for the comment. I'm moving `devel` to `master` in a moment. without bumping the release. next week we will provide an official release.
