### ISSUE TITLE
Can't view a transcript in Trancript View (sleuth_live) using TPM as unit

### ISSUE THREAD

**Issue by apcamargo** [pachterlab/sleuth#113]
I'm using the latest devel.

```
model <- sleuth_prep(df, ~ sex + tissue, min_reads=4, min_prop=0.47,
                            read_bootstrap_tpm = TRUE, extra_bootstrap_summary = TRUE)
model <- sleuth_fit(model)
model <- sleuth_wt(model, 'sexmale')
```

![screenshot from 2017-05-31 16-23-30](https://cloud.githubusercontent.com/assets/22940964/26649826/c28a5bba-461d-11e7-8b20-4234bbbe5675.png)
![screenshot from 2017-05-31 16-23-24](https://cloud.githubusercontent.com/assets/22940964/26649828/c2d7f1fe-461d-11e7-8cd9-07e99b94ca94.png)

**Comment by leiendeckerlu** [comment]
same here for me in the 'gene view' as long as I'm looking at the est_counts, everything is fine but as soon as I switch to tpm I get the "couldn't find target_id ..." error. I'm using the latest version from the devel branch.

**Comment by warrenmcg** [comment]
Try using the latest devel branch of sleuth, and see if the new patches solve this problem.

**Comment by apcamargo** [comment]
I've tested it earlier today, it's working fine. Thank you!

**Comment by leiendeckerlu** [comment]
Yep, indeed this issue is resolved! Thanks!
