### ISSUE TITLE
valid Kallisto .hdf5 output chokes Sleuth

### ISSUE THREAD

**Issue by ttriche** [pachterlab/sleuth#12]
See https://github.com/ttriche/artemisData , i.e. 

```R
library(BiocInstaller)
biocLite("ttriche/artemisData")
?withSleuth  ## run the example
```
Cutting to the chase:
```R
R> so <- sleuth_prep(kal_dirs, covs, ~ condition, target_mapping = t2g)
reading in kallisto results  
......  
normalizing est_counts  
Error: Duplicate identifiers for rows (222, 1166), (671, 1207), (211522, 212466), (211971, 212507), (422822, 423766), (423271, 423807), (634122, 635066), (634571, 635107), (845422, 846366), (845871, 846407), (1056722, 1057666), (1057171, 1057707)
```
I was going to fix this (either by merging TPMs for duplicated rows, or making the rows unique) but dplyr is a little too clever for its own good.  I get a 23-frame stack trace when I run traceback() after running my example in ?artemisData::withSleuth ... may just patch artemis to deal with this prior to alignment, by examining the FASTA files and checking for any duped records.

The problem is that Kallisto doesn't care, so (IMHO) neither should sleuth.  Either make.unique() the rownames, or merge the duplicated ones (in this case, "LTR26B" and "SVA_A", which have slightly different exemplars in RepBase 20_05 humrep.fa vs humsub.fa).  I'd patch it and submit a PR but that's not quite happening... either I need to prevent Kallisto from being run against FASTA files that (together) contain duplicated entries, or sleuth needs to handle this corner case, or perhaps both.

**Comment by pimentel** [comment]
Hi @ttriche,

Thanks for the detailed bug report. 

I'm not sure how I feel about this. I haven't look at the transcripts in question yet, but is there any reason they would have the same name? Do they perhaps differ in their FASTA description?

I feel like kallisto should ensure all TIDs are unique in the index. Any thoughts, @pmelsted?

I can make a temp patch later this week and supply a warning in sleuth, but I feel like adding an arbitrary ID could be confusing to the user. The ordering could be misleading if trying to compare the same annotation with the transcripts shuffled.

**Comment by ttriche** [comment]
I can fix this by scanning the FASTAs for dupes, prior to merging, at the same time as I extract annotations from them with TxDbLite. 

However, when there are dupes (as in RepBase) this will require either merging or a naming convention. Any preference? It seems like this is best handled upstream from sleuth. (Perhaps Kallisto should squawk if it sees dupes?  Indexing the FASTA files and scanning for dupes prior to building the merged .kidx is simple enough, though, and it keeps Kallisto simpler that way.)



--t

**Comment by pmelsted** [comment]
This is really the responsibility of the indexing part of kallisto to refuse duplicated fasta entries. I don't believe that there is a universally good way to resolve this, e.g. by appending something to the name. The best point to alert the user to this problem is for the index to refuse to continue upon seeing a duplicated fasta entry (name, not sequence).

**Comment by ttriche** [comment]
So at least in the case of the user running things through artemis and
BaseSpace, I can handle this during the merge-and-annotate phase where the
transcript-to-gene-bundle and transcript-to-promoter-bundle mappings are
extracted from the Ensembl FASTA files (for repeats and ERCC sequences,
there's no such mapping so we don't bother, but I can still make dupes
unique by changing the entry's name to indicate which FASTA file it came
from).

I can also patch Kallisto to avoid this, but that only makes sense if RSI
and/or commitments make it unlikely that you (plural) will have the time to
do it.

The FASTA-based annotation extraction got new legs yesterday when Matt
McManes found the issue with biomaRt vs. Ensembl FASTA gene IDs for
Drosophila.  It looks like there are several reasons to ensure that
everything is reconciled before proceeding to index a group of FASTAs for
Kallisto.


--t

**Comment by pimentel** [comment]
I propose the following in `kallisto index`

1. Fail indexing if there are duplicate target_ids
2. Add a flag `--force-unique` which will override (1.)

In `sleuth`:

1. Throw a warning if duplicate target_ids for this current version, and make them unique
2. In a few versions discard the warning and throw an error since hopefully everyone will have converted to the new kallisto version

**Comment by pimentel** [comment]
Sorry, meant to say `--force-unique` should make target names unique. Maybe it should be `--make-unique` instead

**Comment by pimentel** [comment]
Ok, I think I've (temporarily) fixed this in d1d18c48a6a62eb6b08cd7cdd98c8bd6b534492f Would appreciate if you could give latest commit in `devel`, @ttriche :)

Thanks!

**Comment by pimentel** [comment]
OK. I just verified. Simply throws a warning now which I think I'm happy with. @pmelsted what do you think about my proposed changes to `kallisto index`?

I'll leave this issue open so we can discuss until we fix it in kallisto.

**Comment by pimentel** [comment]
Fixed in kallisto now:

https://github.com/pachterlab/kallisto/pull/73

Thanks everyone

**Comment by ttriche** [comment]
Sorry... I just de-duped everything in time for it not to matter very much :-/

I'll confirm on my end anyhow 

--t
