### ISSUE TITLE
Feature request: option to filter gene-level analysis specifically at gene level

### ISSUE THREAD

**Issue by warrenmcg** [pachterlab/sleuth#123]
Hi @pimentel,

User @simiii123 asked a question in #122 about filtering at the gene level specifically. Currently, gene-level filtering is done by only aggregating transcripts that pass at the transcript level, but she wants to know if it's possible to only apply a filter at the gene-level. I'll quote her comment in full:

> In sleuth, filtering is only possible on transcript level. Is there a reason why applying the following steps to sleuth object (aggregated by gene) is wrong :
> extract raw_counts from sleuth
> aggregate by gene
> apply expression cutoff (e.g. 10 counts)
> filter so_gene$bs_summary$... by expression list passing filter
> run models ...
> It works, and in the models the reduced set is used. But is there any stats prior to running the model that are invalid now?

Now, the answer to her question (I think) is that there are no previous stats that are invalid. However, my _prima facie_ sense is that filtering at the transcript level versus applying the same filter at the gene-level would not always be equivalent (e.g. multiple transcripts that would fail the filter could aggregate to a gene that would pass the filter at the gene-level, when otherwise the gene would be excluded with all of its transcripts filtered out).

What are your thoughts on providing that flexibility for the user? I think could be implemented relatively easily, but we would have to be careful about provenance (how would someone know looking at a processed sleuth object whether how it was filtered).

**Comment by pimentel** [comment]
hm. I have some ideas on this... perhaps we can chat about them and our next meeting?

**Comment by pimentel** [comment]
not really relevant anymore since we are doing gene aggregation. closing for now.
