### ISSUE TITLE
Subsetting list of transcripts in sleuth to avoid wrongful read assignment in Kallisto

### ISSUE THREAD

**Issue by agropyron** [pachterlab/sleuth#131]
I am working on a de novo transcriptome of two gamma-Proteobacteria, which were both present in each of my samples. The abundance of one bacterium does not vary between samples, while the abundance of the other bacterium varies strongly. In the DE analysis it is therefore essential to normalize library size for each of the bacteria separately. 

With Kallisto I first tried mapping the entire pool of reads to the transcripts of both bacteria, and afterwards to only the transcripts of one bacterium at a time. I found that in the latter case it seems that the transcripts of one bacteria also attracted reads of the other bacterium, and that the amount of reads wrongfully mapped varies between treatments. 

Ideally I could map against all transcripts with Kallisto to avoid spurious mapping, and then tell sleuth_prep to only use a subset of the target_ids for normalisation and analysis. I tried to achieve this manually by subsetting the abundance.tsv file with awk (awk 'NR==1 || /BactA_/ {print}' abundance.tsv>abundance_bactA.tsv) -  I get .tsv files with only the transcripts of one bacterium without any issues. Yet for the abundance.h5 files this approach is not possible, and it seems that sleuth_prep extracts all transcripts present in the .h5 file to do the normalization steps :( . Could it be made possible that sleuth_prep only extracts target_ids it finds in the .tsv file from the .h5 files? Or is there a way to subset the .h5 file by a pattern contained in the traget_id? 

(For now I am going to try subsetting my pool of reads by bacteria (hopefully I can use the pseudobam output of kallisto quant), and reinput the subset pools separately into kallisto. Fingers crossed!)

**Comment by roryk** [comment]
Hi @agropyron,

I haven't tried this, but looking at the code, there are two functions, read_kallisto and write_kallisto in sleuth. Could you read in the h5 file with read_kallisto, subset it and write it out to a new file, and then use it the way you would normally on the new file?

**Comment by agropyron** [comment]
Hi @roryk , 
Thank you for the suggestions, they got me halfway there! 
read_kallisto does allow me to grep out my transcripts of interest. Since I did not find the function write_kallisto in this master, I dug up a "write_kallisto_hdf5" fuction (old?) from here https://rdrr.io/github/pachterlab/sleuth/src/R/read_write.R . However, when I try to save my filtered table, R complains: 
>Error: Error in h5checktype(). Argument not of class H5IdComponent. 

I don't find the reason why the function fails to write the output file into a proper .h5, though. 

I did not change the "bias_normalized", "bias_observed", and "fld" tables since they have only 1000 elements (my dataset contains ~50k transcripts). I wonder whether these tables are going to be used be sleuth_prep?

>My R code (f contains the path to the file, f2 the path to a new file (but I also tried overwriting the original file with no success): 

>test<-read_kallisto(f, read_bootstrap = T)
>test$abundance<-test$abundance[grep("Bu_",test$abundance$target_id),]
>for (i in c(1:100)){
>  test$bootstrap[[i]]  <-test$bootstrap[[i]] [grep("Bu_",test$bootstrap[[i]]$target_id),] 
>}
>write_kallisto_hdf5(test, f2, overwrite=T, write_bootstrap = T)

**Comment by warrenmcg** [comment]
I will not be able to propose a solution quickly (swamped with work trying to handle a few deadlines), but I can briefly answer why @agropyron has this issue: the API for the rhdf5 package that is used for both `read_kallisto` and `write_kallisto_hdf5` went through an overhaul that broke the current write method, which is why it isn't part of the sleuth package at the moment. You are getting this error because the old `write_kallisto_hdf5` is assuming the old API and not the new one. I had attempted to put something together to write HDF5 files for testing purposes, and I have a partial solution, but a fully working one. I'll try to get to this next week, along with tackling some of the other issues that so far have been given adequate attention.

If you have time, @agropyron, you can take a look at the new API ([link](https://bioconductor.org/packages/release/bioc/html/rhdf5.html)) and see if you can make some headway on your own. If you cannot, don't worry.

**Comment by roryk** [comment]
Thanks @warrenmcg, that is super helpful.

**Comment by agropyron** [comment]
Thank you @warrenmcg! I am at a conference and stressing about my talk, but I'll give it a go on my way home!

**Comment by agropyron** [comment]
Below functions has worked in my test runs. My comments are marked with ####. Caution: I did not understand or address one of the TODOs and am still completely clueless about what the createDataset step actually does. **Futhermore I have not yet checked whether sleuth_prep uses fld, bias_observed or bias_normalised** and whether these can be safely ignored when subsetting kallisto files.

```
write_kallisto_hdf5 <- function(kal, fname, overwrite = TRUE, 
                                   write_bootstrap = TRUE, compression = 6L) {
  stopifnot( is(kal, "kallisto") )
  stopifnot( is(fname, "character") )
  stopifnot( is(compression, "integer") )
  stopifnot( length(compression) == 1 )
  
  # TODO: ensure that all bootstraps are sorted according to abundance
#### I did not understand or address this TODO
  
  if (compression < 0 || compression > 7 ) {
    stop("'compression' must be in [0, 7]")
  }
  
  fname <- path.expand(fname)
  
  if (file.exists(fname)) {
    if (overwrite) {
      warning(paste0("'", fname, "' already exists. Overwriting."))
      file.remove(fname)
    } else {
      stop(paste0("'", fname, "' already exists."))
    }
  }
  
  if ( !rhdf5::h5createFile( fname ) ) {
    stop(paste0("Error: Couldn't open '", fname, "' to write out."))
  }
  
  dims <- c(nrow(kal$abundance), 1)
  cat("dims: ", class(dims), "\n")
  
  # write out auxilary info
  rhdf5::h5createGroup(fname, "aux")


  # stopifnot( rhdf5::h5writeDataset(fname, "aux/ids", dims = dims,
  #                                  storage.mode = "character", size = 100, level = compression) )  ##I wasn't sure what was attempted here, but it caused an Error
  
#### Above writeDataset caused an Error in sleuth_prep. 
#### Even though I do not understand why step is needed,
#### with createDataset there is no error:
  stopifnot( rhdf5::h5createDataset(fname, "aux/ids", dims = dims,
                                   storage.mode = "character", size = 100, level = compression) ) 

  if (write_bootstrap) {
    rhdf5::h5write(length(kal$bootstrap), fname, "aux/num_bootstrap")
  } else {
    rhdf5::h5write(0L, fname, "aux/num_bootstrap")
  }

  rhdf5::h5write(kal$abundance$target_id, fname, "aux/ids")
  rhdf5::h5write(kal$abundance$eff_len, fname, "aux/eff_lengths")
  rhdf5::h5write(kal$abundance$len, fname, "aux/lengths")
  rhdf5::h5write(kal$fld, fname, "aux/fld")
  rhdf5::h5write(kal$bias_normalized, fname, "aux/bias_normalized")
  rhdf5::h5write(kal$bias_observed, fname, "aux/bias_observed")
  rhdf5::h5write(attributes(kal)$num_processed, fname, "aux/num_processed")
  rhdf5::h5write(attributes(kal)$index_version, fname, "aux/index_version")
  rhdf5::h5write(attributes(kal)$kallisto_version, fname, "aux/kallisto_version")
  rhdf5::h5write(attributes(kal)$start_time, fname, "aux/start_time")
  rhdf5::h5write(kal$abundance$est_counts, fname, "est_counts")
  
  if (write_bootstrap && length(kal$bootstrap) > 0) {
    rhdf5::h5createGroup(fname, "bootstrap")
    for (i in seq_along(kal$bootstrap)) {
      bs <- kal$bootstrap[[i]]$est_counts
      bs_name <- paste0("bootstrap/bs", i-1)    
####if not i-1: .Error in rhdf5::h5read(fname, paste0("bootstrap/bs", i - 1)) : 
####Object bootstrap/bs0 does not exist in this HDF5 file.
      rhdf5::h5write(bs, fname, bs_name)
    }
  }
  
  invisible(kal)
}
```

To subset files supply below loops with:
- a vector (PATH) with all paths to kallisto directories that contain the abundance.h5 and abundance.tsv files
- a pattern (PATTERN) to extract transcripts of one organism from kallisto files

WARNING: THIS WILL OVERWRITE THE ORIGINAL FILES! A back-up is strongly recommended. 

```
for (j in PATH){
  f=paste0(j,"/abundance.h5")
  H5<-read_kallisto(f, read_bootstrap = T)
  grep_pattern<-"PATTERN"
  H5$abundance<-H5$abundance[grep(grep_pattern,H5$abundance$target_id),]
  for (i in c(1:100)){
    H5$bootstrap[[i]] <-H5$bootstrap[[i]] [grep(grep_pattern,H5$bootstrap[[i]]$target_id),]
  }
  write_kallisto_hdf5(H5,f, overwrite=T, write_bootstrap=T, compression=6L)
}

for (j in PATH){
  f=paste0(j,"/abundance.tsv")
  TSV<-read.table(f, header=T)
  grep_pattern<-"PATTERN"
  TSV<-TSV[grep(grep_pattern,TSV$target_id),]
  write.table(TSV, f, append=F, quote=F, sep="\t", row.names=F, col.names = T)
}
```

**Comment by agropyron** [comment]
... and I just realised that above functions only works if library rhdf5 is loaded. Weird.

**Comment by warrenmcg** [comment]
@agropyron, Thanks for efforts on this and apologies for my delay in responding. I'll be taking a look at this over the next few weeks, and see what we can do to get this into the next release.

**Comment by pimentel** [comment]
@agropyron I looked through your code and it certainly seems like a reasonable solution to me. I am pretty sure you don't have to worry about the fragment length distribution or bias parameters in `sleuth_prep` but you might run into some issues with some of the visualizations (specifically the relevant figures in Shiny). I haven't ran your code, but if `sleuth_prep` runs correctly then I imagine it will probably be fine.

@warrenmcg is this something you were thinking about putting into the next release? let's talk about it at our next meeting.

**Comment by agropyron** [comment]
@pimentel Thank you!

**Comment by warrenmcg** [comment]
Hi guys,

Excellent work @agropyron!

I found the issue with why `rhdf5` needs to be loaded via `library` for the function to work. It's an issue with how the NAMESPACE for rhdf5 was written, as discussed in this [StackOverflow thread](https://stackoverflow.com/questions/30778718/how-to-use-s3-methods-from-another-package-which-uses-export-rather-than-s3metho).

Thus, we should follow the recommendation of the answer provided on that thread, and add `importFrom` statements in front of the function like this:
```
#' @importFrom rhdf5 h5write.default
#' @importFrom rhdf5 h5write
#' @export
write_kallisto_hdf5 <- function(...) [[etc.]]
```

Also, I think it's important for us, if we are going to allow people to subset their kallisto files, to keep as much of the structure untouched as possible, meaning we should make sure the fragment length distribution and bias parameters are included. If they are omitted, `sleuth_prep` will not fail because they are not used. However, there will be no indication that the `kallisto` object will have changed, with empty bias parameters and fragment length distributions.

So, we should incorporate this write function while also making sure to write out the bias and fragment length info, but we should also write a "subsetting" function to produce a modified kallisto object.

**Comment by pimentel** [comment]
Fixed by @warrenmcg and now in `devel`. Should be in `master` in a day or so.

Thank you, @warrenmcg!

**Comment by pimentel** [comment]
Ah, much longer than a day (sorry), but should be coming tomorrow
