### ISSUE TITLE
Error: unexpected end of input

### ISSUE THREAD

**Issue by mictadlo** [pachterlab/sleuth#136]
Hi,
Did you run into the following error:
```
  reading in kallisto results
  dropping unused factor levels
  ..............................
  normalizing est_counts
  33052 targets passed the filter
  normalizing tpm
  merging in metadata
  summarizing bootstraps
  ..............................
  fitting measurement error models
  shrinkage estimation
  computing variance of betas
  fitting measurement error models
  shrinkage estimation
  computing variance of betas
  Error: unexpected end of input
  Execution halted
```

with the following code:

```
library("sleuth")


sample_id <- dir(“kallisto”)
sample_id

kal_dirs <- sapply(sample_id, function(id) file.path(“kallisto”, id))
kal_dirs

s2c <- read.table(“/work/lorencm/Chrissie/kallisto-nf/work/22/034bc891dd044f5651c9a9ae29d932/pheno_table.txt”, header = TRUE, stringsAsFactors=FALSE)
s2c <- dplyr::select(s2c, sample = ids, Tissue_type, condition)
s2c <- s2c[order(s2c$sample), ]
s2c <- dplyr::mutate(s2c, path = kal_dirs)

print(s2c)

t2g <- read.table(“/work/lorencm/Chrissie/diamond/t2g.txt”, header = TRUE, stringsAsFactors=FALSE)

# Load the kallisto processed data into the object
so <- sleuth_prep(s2c, ~ condition, target_mapping = t2g, extra_bootstrap_summary = TRUE)

# Estimate parameters for the sleuth response error measurement (full) model 
so <- sleuth_fit(so)

#Next, we fit the reduced model. In this case, the reduced model is the intercept-only model
so <- sleuth_fit(so, ~1, 'reduced')
print("Done sletu_fit")

#and finally perform the test:
so <- sleuth_lrt(so, 'reduced', 'full')
print("DONE sleut_lrt")
models(so)

saveRDS(so, file=paste("sleuth_object.rds")
```

What did I miss?

Thank you in advance.

Michal

**Comment by lynnyi** [comment]
Hey Michael,

You may have figured this out by now, but you’re missing a end parentheses at the end of your Rscript (i.e. this is a R syntax error, not a sleuth-generated error). You might also want to check whether you just wanted to write

saveRDS(so, file = ("sleuth_object.rds”))


Instead of

saveRDS(so, file = paste("sleuth_object.rds”))


Best,
Lynn


On Aug 27, 2017, at 11:47 PM, Michał T. Lorenc <notifications@github.com<mailto:notifications@github.com>> wrote:


  Error: unexpected end of input

**Comment by mictadlo** [comment]
Hi,
Thank you, it works now. What is the correct way to store `so` object:

- saveRDS(so, file = ("sleuth_object.rds”))
- saveRDS(so, file=paste("sleuth_object.rds"))
- save(so, file=paste("sleuth_object.so"))

Thank you in advance.

Michal

**Comment by warrenmcg** [comment]
Hi @mictadlo,

Any of those are appropriate, but if you use `saveRDS`, you have to use `loadRDS` to get the object back into R, whereas you have to use `load` if you used `save`. The current devel version of sleuth has convenient wrappers named `sleuth_save` and `sleuth_load` to use `saveRDS` / `loadRDS`.

Also, for the first option, the parentheses are unnecessary. You can just do `saveRDS(so, file = "sleuth_object.rds")`.

I'm going to close this issue. Feel free to open it if you have further questions about using `saveRDS` vs `save`. If you discover a different issue, please open a new ticket. Thanks!
