### ISSUE TITLE
Error in order(indices)

### ISSUE THREAD

**Issue by philge** [pachterlab/sleuth#137]
Hi

Following code is giving error

sample_to_condition <- METADATA %>% dplyr::rename(sample = ID)
rownames(sample_to_condition) <- sample_to_condition$sample
sample_to_condition <- sample_to_condition[sample_id,]
s2c <- dplyr::mutate(sample_to_condition, path = kal_dirs)

so <- sleuth_prep(s2c, extra_bootstrap_summary = TRUE)

reading in kallisto results
dropping unused factor levels
............................................................................................................................................................................................................................................................................
normalizing est_counts
100408 targets passed the filter
normalizing tpm
merging in metadata
summarizing bootstraps
....................................................
............................................................................
...............................................
.............................................Error in order(indices) : unimplemented type 'list' in 'orderVector1'

Please help me to fix the issue.

Thanks
Philge Philip

**Comment by philge** [comment]
Hi

I was running the code on Amazon EC2. It seems error is because of some broken parallel processing. When i re-run the code with parameter num_cores=2, code run without error.

Thanks
Philge

**Comment by warrenmcg** [comment]
Hi @philge, if there are no more issues, I'm going to close this. If you experience a similar issue, please feel free to reopen the issue. Thanks!

**Comment by xqrongm** [comment]
I'm having the same problem as described in the original post. I tried several values of `num_cores` including 1, 2, 20, 28 (there are 28 cores available on my node), all gave me the same error.

**Comment by warrenmcg** [comment]
Hi @xqrongm,

Could you tell me what version of sleuth you are running (if you are running a devel version, please tell me which commit you are using)?

Also, you are getting the exact same error when you set `num_cores = 1`? If it's not exact same error, can you show what the precise error is.

Once you answer those questions, that will help us decide if this is a new issue or to re-open this old one. Thanks!

**Comment by xqrongm** [comment]
version 0.29.0

Yes, I'm getting the exact same error for `num_cores = 1,2,20,28`:
```
reading in kallisto results
dropping unused factor levels
.....................................................................................................................................................................................................................................................................................................................................................................................................................................................................................
normalizing est_counts
80030 targets passed the filter
normalizing tpm
merging in metadata
aggregating by column: ensembl_gene_id
21832 genes passed the filter
summarizing bootstraps
........................................................................
..............Error in order(indices) : unimplemented type 'list' in 'orderVector1'
```
Thanks!

**Comment by MDSharma** [comment]
Hi,

this issue seems closed but I seem to be getting it as well with the latest build, when using more than one factor in the model:

'''
> so2 <- sleuth_prep(s2c, ~ population + day, num_cores = 1)
reading in kallisto results
dropping unused factor levels
..................................
normalizing est_counts
66490 targets passed the filter
normalizing tpm
merging in metadata
summarizing bootstraps
................................
.
Error in identical(indices, order(indices)) :
  unimplemented type 'list' in 'orderVector1'
'''
