### ISSUE TITLE
sleuth_results manpage does not document likelihood ratio result columns

### ISSUE THREAD

**Issue by cbrueffer** [pachterlab/sleuth#142]
The sleuth_results manpage only documents the Wald test result table columns, not the ones for the likelihood-ratio test.

**Comment by warrenmcg** [comment]
Thanks for pointing this out. This will be addressed in an upcoming release.
If you need help with understanding the columns right now, the ones unique to LRT are the following:
+ `test_stat` this is the ratio of the likelihoods of the two models
+ `rss` this is the residual sum of squares for the 'null model' (i.e. the less complex model)
+ `degrees_free` this is the number of degrees of freedom lost when using the more complex 'alternative model'

**Comment by pimentel** [comment]
thanks for the report @cbrueffer and thanks for the fixes @warrenmcg. it is now merged in the development version.
