### ISSUE TITLE
Error while working on sleuth in Linux

### ISSUE THREAD

**Issue by vasanthmandla** [pachterlab/sleuth#149]
I am trying to run the sleuth in Linux environment . But, I am facing this error. kindly help to resolve this error. 

Calls: sleuth_prep ... tryCatch -> tryCatchList -> tryCatchOne -> <Anonymous>
Execution halted

Thanks,
Vasanth

**Comment by warrenmcg** [comment]
Hi @vasanthmandla,

Thanks for using sleuth! We need more information to be able to help you. I'm afraid we can't help identify the problem without this additional information.

Could you provide the code you used to call `sleuth_prep` and full output of messages from right after you call `sleuth_prep` until you get the error message? It should look something like this:
```
so <- sleuth_prep(s2c, target_mapping = t2g)
reading in kallisto results
dropping unused factor levels
.........
[[etc.]]
Error
```

We need the full output before we can start. Thanks!

**Comment by warrenmcg** [comment]
pinging @vasanthmandla: just wanted to check in to see if you could give us more information so we could help you? Thanks

**Comment by pimentel** [comment]
one last ping before we close this. could you provide any more info, @vasanthmandla?


thanks

**Comment by vasanthmandla** [comment]
Thank you very much for the follow-up. This issue was resolved.
