### ISSUE TITLE
Support for other normalization factors

### ISSUE THREAD

**Issue by pimentel** [pachterlab/sleuth#15]
As requested in the [Google group](https://groups.google.com/forum/#!topic/kallisto-sleuth-users/Vq6MpLfObro), we should support other normalization factors. Here are some possibilities:
1. Take a function and perform normalization in `sleuth_prep`
2. Add `normalize` flag in `sleuth_prep`. If FALSE, then don't perform any normalization, but require user to normalize afterwards with `sleuth_normalize` (doesn't exist yet)
   - This function could do alternative normalizations such as spike ins
3. Simply take alternative 'normalization factors' that are spit out from other methods

I'm kind of tempted to use a mix of 2 and 1, where `sleuth_normalize` can take a function, or a list of spike ins, etc.

**Comment by ttriche** [comment]
Suggestion:

1) have the normalization hook for sleuth_prep default to calling sleuth_normalize (with a defined API)
2) if you want a null normalization, have a function (maybe sleuth_unnormalized) pass through the data
3) any other function that might be called just needs to follow the API for sleuth_normalize.

This has been done before, e.g. in Minfi for normalizing DNA methylation arrays (http://bioinformatics.oxfordjournals.org/content/30/10/1363).  It's a good way to decouple the steps that typically serve as open research questions from those that are directly addressed by the work (i.e., sleuth directly addresses variance partitioning using the bootstrap replicates to disambiguate biological from technical uncertainty, but the downstream work of normalization for systematic variation or experiment design shortcomings, along with biological interpretation, is in some senses out of scope). 

JMHO, but in some sense these are the same principles behind artemis, which is to say, we take care of the boring schlep work of de-duping FASTAs, mapping transcripts to genes and IDs, pathway annotation, and enrichment, and we avoid touching the areas where Kallisto or Sleuth excel.

**Comment by pimentel** [comment]
@ttriche as usual, these are all good points. thanks! Perhaps we should chat later this week by phone to see how we can work together on these (and other) points?

**Comment by a-slide** [comment]
I might have missed the it, but was the functionality implemented in the last version of Sleuth ? maybe with the by replacing the default function arg `norm_factors` from `norm_fun_counts` and `norm_fun_tpm` by an dedicated function ?

**Comment by warrenmcg** [comment]
@pimentel, ok to close this?
