### ISSUE TITLE
unused argument in `(total = .(total = sum(est_counts)))` for new check zero code

### ISSUE THREAD

**Issue by warrenmcg** [pachterlab/sleuth#151]
It was reported in a private email, and recognized by user @petersbr ([commit link](https://github.com/petersbr/sleuth/commit/c6a75e3f30f3e29c7712fd30177f1e49c5a9ebb1)), that the new check zero code included from pull request #144 has a bug in it.

The fix suggested by @petersbr will be incorporated into pull request #150, unless @pimentel has a different suggestion.

**Comment by Abiterkuile** [comment]
Hi there, I've been having this issue as well;

> so <- sleuth_prep(s2c, extra_bootstrap_summary = TRUE)
reading in kallisto results
dropping unused factor levels
.............................
Error in `[.data.table`(counts_test, , total = .(total = sum(est_counts)),  : 
  unused argument (total = .(total = sum(est_counts)))

I'm new to sleuth so not sure how to apply this fix. Could you please give me some guidance as to how I can resolve this?

**Comment by pimentel** [comment]
This should be fixed in the `devel` branch now, @Abiterkuile. If you are eager you can test it, otherwise, it should be integrated into the master branch tomorrow.

If you are still having issues with it please let us know.
