### ISSUE TITLE
Contrast type function in Sleuth

### ISSUE THREAD

**Issue by JoanaBSilvestre** [pachterlab/sleuth#156]
Hi,
I'm trying to do multiple comparisons in my dataset.
The experiment design is consist of 4 conditions (A, B, C and D).
To compare A to B, A to C and A to D is easy. However, is there any contrast type of functions that can be used to compare B to C, for example?
I can run different sleuth objects, but that doesn't seem like a good idea.
Thanks you
Joana

**Comment by warrenmcg** [comment]
Unfortunately, there is not currently a way to implement arbitrary contrasts in sleuth because of the nature of how it runs the linear modeling.

However, if you are only interested in binary comparisons, there is a way for you to compare B to C after having done A to the others.

Let's say your `samples_to_covariates` table looks like this:
```
sample   condition
sample_1 A
sample_2 A
sample_3 B
sample_4 B
sample_5 C
sample_6 C
sample_7 D
sample_8 D
```
and you did the following to do the comparisons to A:
```
## whatever your full call to sleuth_prep is; this is just an example
so <- sleuth_prep(s2c, full_model = ~condition, target_mapping = t2g)
so <- sleuth_fit(so)
so <- sleuth_fit(so, ~1, 'reduced')
so <- sleuth_lrt(so, 'reduced', 'full')
# as an example; you would replace 'B' with whatever the condition name is, e.g. 'conditionKO'
so <- sleuth_wt(so, 'conditionB')
so <- sleuth_wt(so, 'conditionC')
so <- sleuth_wt(so, 'conditionD')
```

If you want to now compare some of the other conditions to 'B', you can do one of the following options:
```
new_s2c <- so$sample_to_covariates
new_s2c$condition <- as.factor(new_s2c$condition)
new_s2c$condition <- relevel(new_s2c$condition, ref = "B") ## or whatever condition 'B' is

## the new_s2c table now has B as the reference level, instead of A in the default
## option 1: start a new sleuth object; valid because the normalization will be the same
so2 <- sleuth_prep(new_s2c, full_model = so$full_model)
so2 <- sleuth_fit(so2)
so2 <- sleuth_fit(so2, ~1, 'reduced')
so <- sleuth_lrt(so, 'reduced', 'full')
so <- sleuth_wt(so, 'conditionC') # this will compare C to B, since B is the new reference level
so <- sleuth_wt(so, 'conditionD') # this will compare D to B

## option 2: keep the old model with A as ref alongside the new model with B as ref
so2 <- so
so2$sample_to_covariates <- new_s2c
new_model <- model.matrix(so$full_model, new_s2c)
rownames(new_model) <- new_s2c$sample
so2$design_matrix <- new_model
new_fit_name <- 'fullB' ## or whatever you want the new name to be
so2 <- sleuth_fit(so2, fit_name = new_fit_name)
so2 <- sleuth_wt(so2, 'conditionC', which_model = new_fit_name) ## or whatever condition 'C' is
so2 <- sleuth_wt(so2, 'conditionD', which_model = new_fit_name) 
so2 <- sleuth_lrt(so2, 'reduced', new_fit_name)
```

The latter example is more complicated because you'll have one model based on the original A reference level ('full'), and another model based on B as the reference level ('fullB'). The model matrix will refer to the new reference level, so anything further work will be based on that.

Hope that helps as a workaround!

**Comment by JoanaBSilvestre** [comment]
Thank you for the reply! This was very helpful

**Comment by domi84** [comment]
Hi, I have the same issue and I am using sleuth 0.29 .
I was trying to follow the option 1, but something is going wrong.

First of all:

```
>so2 <- sleuth_prep(new_s2c, full_model = so$full_model)
Error in sleuth_prep(new_s2c, full_model = so$full_model) : 
  'new_s2c' (sample_to_covariates) must contain a column named 'path'
```

 
what I have done is add the path from the old s2c
```
>new_s2c$path <- as.character(s2c$path)
>so2 <- sleuth_prep(new_s2c, full_model = so$full_model)
reading in kallisto results
dropping unused factor levels
.............
normalizing est_counts
18578 targets passed the filter
normalizing tpm
merging in metadata
summarizing bootstraps
.............
Warning message:
In check_num_cores(num_cores) :
  It appears that you are running Sleuth from within Rstudio.
Because of concerns with forking processes from a GUI, 'num_cores' is being set to 1.
If you wish to take advantage of multiple cores, please consider running sleuth from the command line.
```

But another error appear:
```
> so2 <- sleuth_fit(so2)
Error in sleuth_fit(so2) : 
  'formula' was not specified and the 'full' model was not specified in `sleuth_prep`. Please specify a formula and a label.
```

why `so2 <- sleuth_prep(new_s2c, full_model = so$full_model)` is not working?
and actually:
```
> so$full_model
NULL 
```

What am I doing wrong?
Thanks

**Comment by benkraj** [comment]
@domi84 

I'm running into the same issue as you. Were you able to sort this out?

Thanks

**Comment by domi84** [comment]
Hi,
I looked back to my notes, I think it worked with this. You have to make a new meta coping the meta info:
```
new_meta <- so$sample_to_covariates
new_meta$condition <- as.factor(new_meta$condition)
new_meta$path <- as.character(meta$path)
```
and then change your intercept:
`new_meta$condition <- relevel(new_meta$condition, ref = "B")`

then make a new so and copy/load the full model so
`so2 <- sleuth_prep(new_meta, full_model = so$full_formula)`

and then run it:
```
so2 <- sleuth_fit(so2)
so2 <- sleuth_wt(so2, 'C') # this will compare C to B, since B is the new reference level
so2 <- sleuth_wt(so2, 'D')
```

I didn't receive any confirm this is the best way to do it though...
