### ISSUE TITLE
Kallisto - How to change number of bootstraps?

### ISSUE THREAD

**Issue by BIOProgrammer21** [pachterlab/sleuth#161]
Hello, 

I am using Kallisto and was wondering how to correctly set the number of bootstraps to 100?

In the Kallisto Quant PE under options, do I set the number of threads to 100 in addition to the number of bootstrap samples?

Any help is appreciated

**Comment by warrenmcg** [comment]
It seems like you posted this exact question on the google forum and here. In general, it is strongly discouraged on website forums to "cross-post" questions (see [this post](https://meta.stackexchange.com/questions/64068/is-cross-posting-a-question-on-multiple-stack-exchange-sites-permitted-if-the-qu), especially [this comment](https://meta.stackexchange.com/a/243797), for more information on the topic of cross-posting). In general, you should pick the forum that is most suited for the question.

In this case, this is not a bug report or issue with the software, but rather a usage question. Thus, it is most applicable to just focus on the google forum for usage questions like this. I will answer your question on the google forum, but in the future, please keep in mind where your question is most appropriate. We do our best to answer every question and issue that comes in the appropriate forum.

Thanks for using kallisto and sleuth!

**Comment by BIOProgrammer21** [comment]
My apologies, thank you for the response
