### ISSUE TITLE
Current sleuth_prep procedure doesn't record number of bootstraps present

### ISSUE THREAD

**Issue by warrenmcg** [pachterlab/sleuth#166]
@pimentel, a new minor issue that should be addressed before the next major release:

A user on the google group (see [the relevant thread](https://groups.google.com/forum/#!topic/kallisto-sleuth-users/puSTHUhSars)) was concerned about missing bootstraps when viewing the summary table for his sleuth object on the shiny App. There were no other error messages.

After working with one of his HDF5 files, I realized that the current procedure in `sleuth_prep` skips over recording how many bootstraps are present, so that the `obj$kal` kallisto list will always have an empty/`NULL` list for the `kal$bootstrap`. So, this means the summary method (see [the relevant line of code](https://github.com/pachterlab/sleuth/blob/8308dfd6bcbcaf3a114ae222ab2f9ed61d881a73/R/sleuth.R#L763)) will always return zero.

This is probably easy to fix (always record the number, and make it an attribute of the kallisto object that is directly checked in the summary method), but there is some ambiguity: do we want to always report the number of bootstraps present? Or if the user sets `max_bootstrap`, do we want to report the actual number used? Or should we report both?

**Comment by pimentel** [comment]
Fixed by @warrenmcg 💯
