### ISSUE TITLE
Release version for p-value aggregation features

### ISSUE THREAD

**Issue by johnomics** [pachterlab/sleuth#167]
I see the p-value aggregation paper is now [fully published](https://genomebiology.biomedcentral.com/articles/10.1186/s13059-018-1419-z) - please could you release a proper sleuth version to match the features in this paper? It's much nicer to cite a real version rather than a GitHub commit on the devel branch. Also, we are very reluctant to install devel commits on production machines with many users, but we have users wanting to use these features. If you believe this code is robust, please could you release it?

**Comment by lynnyi** [comment]
Hi John,

Thank you for your interest.  We are actively working on releasing the p-value aggregation feature and are very excited about it, but want to make sure we squash any remaining bugs and have the documentation ready for a wider general audience who may not be familiar with this feature. We expect this next release of sleuth to happen within the next two weeks.


Thanks for your patience,
Lynn

**Comment by johnomics** [comment]
Hi Lynn - many thanks for your reply, it's great to hear a release is coming. Best wishes, John
