### ISSUE TITLE
Error in bs_mat[, which_ids]

### ISSUE THREAD

**Issue by Rdroit** [pachterlab/sleuth#169]
Hi,

I was using a pipeline using Salmon Wasabi and Sleuth when i encountered this error:

Meta data loaded
Arguments parsed
reading in kallisto results
dropping unused factor levels
.........
normalizing est_counts
21061 targets passed the filter
normalizing tpm
merging in metadata
aggregating by column: ens_gene
12956 genes passed the filter
summarizing bootstraps
.Error in bs_mat[, which_ids] : indice out of bounds
Calls: <Anonymous> ... apply_function -> FUN -> process_bootstrap -> <Anonymous>
moreover : Warning message:
Column `target_id` joining character vector and factor, coercing into character vector 
Execution stopped

the traceback in R is : 

> traceback()
5: matrixStats::colVars(bs_mat[, which_ids])
4: process_bootstrap(i, samp_name, kal_path, num_transcripts, est_counts_sf[[i]], 
       read_bootstrap_tpm, ret$gene_mode, extra_bootstrap_summary, 
       target_id, mappings, which_ids, ret$gene_column, ret$transform_fun)
3: FUN(X[[i]], ...)
2: apply_function(seq_along(kal_dirs), function(i) {
       samp_name <- sample_to_covariates$sample[i]
       kal_path <- get_kallisto_path(kal_dirs[i])
       process_bootstrap(i, samp_name, kal_path, num_transcripts, 
           est_counts_sf[[i]], read_bootstrap_tpm, ret$gene_mode, 
           extra_bootstrap_summary, target_id, mappings, which_ids, 
           ret$gene_column, ret$transform_fun)
   })
1: sleuth::sleuth_prep(opt$meta, target_mapping = opt$t2g, aggregation_column = "ens_gene", 
       num_cores = threads)

Do someone have an idea of what is going on here ?? 
Thanks :)

**Comment by Rdroit** [comment]
Thank you a lot @warrenmcg  :D 
you saved me, it fixed my problem.
sorry for the time of response.

**Comment by pimentel** [comment]
I think this is fixed, no? @warrenmcg

**Comment by warrenmcg** [comment]
@pimentel: yes this is fixed. I had opened it again because I hadn't made the commit. Since the commit is now included, it can be closed.
