### ISSUE TITLE
sleuth_to_matrix returns columns in random order

### ISSUE THREAD

**Issue by vegardny** [pachterlab/sleuth#174]
This might be a feature since it is deliberately done:

s_data <- s_data[, sample(1:ncol(s_data))]

However this behaviour is undocumented and may lead to users errors.

i use sleuth_0.29.0

**Comment by pimentel** [comment]
Ugh. That's an artifact of testing from a bugfix a while ago... Fixing this also uncovered some other nasty bugs. Anyway, fixed in `devel` and coming in the imminent v0.30.0 release.

Thanks for reporting
