### ISSUE TITLE
read_kallisto_h5 detects non-unique target_ids

### ISSUE THREAD

**Issue by channsoden** [pachterlab/sleuth#176]
Hello,

When attempting to run sleuth_prep I get a very long series of error messages stating:

```
Warning message in read_kallisto_h5(kal_path$path, read_bootstrap = read_bootstrap, :
“Some target_ids in your kallisto index are exactly the same. We will make these unique but strongly suggest you change the names of the FASTA and recreate the index. These are the repeats: ”

```
Often the list of repeats is empty, as above, but sometimes it is a very long series of unknown symbols. E.g.:

```
These are the repeats: ֓, ؙ, ؖ, ؅, , , , ,	<b4>, 	<c4>,	<f5>,
., (<8c><d0>*, (<8d>n, (<8e><b1>, (<8f>), (<94><e2>, (<97><e2>, (<99><b1>, (<9b>, (<9c><b1>, (<9c><e9>, (<9f>, (<9f><9e>/, (<9f><e9>, (<a2>, (<a5>, (<a9>, (<aa>, (<b1><81>, (<b1><a5>, (<b4>, (<b4>, (<b8>f, (<b9>N, (<ba><93>, (<bb>f, (<c4>, (<c4> , (<cb>2, (<cf><d2>), (<d0>*, (<d2>2, (<d3>), (<d3><d2>), (<d4><c3>, (<d6>, (<d6><d2>), (<dd><d2>), (<e0><f2>, (<e0>2, (<e4><87>, (<e4>2, (<e7>2, (<e8>
, (kx., (l<9e>/, (Ln, (n, (n, (n<b4>, (nn, (o<9e>/, (o<c4> , (p<b1>, (P<c4> , (P<e9>, (Q<b1>, (Q<c0>, (R<b4>, (r<c4> , (rn, (U, (U), (ux., (V<b4>, (Vx., (x., (x., (Y<b4>, . . . etc for several pages
```

The function finally ends with:

```
Error in all.equal(obs_raw$target_id, obs_norm$target_id) && all.equal(obs_raw$sample, : invalid 'x' type in 'x && y'  
Traceback:

1. sleuth_prep(design, extra_bootstrap_summary = TRUE)  
2. stopifnot(all.equal(obs_raw$target_id, obs_norm$target_id) &&   
 .     all.equal(obs_raw$sample, obs_norm$sample))  
```

Are the target_ids the IDs of the target transcripts in my reference fasta? Because I checked those, and they are in fact all unique. Furthermore, all these samples are using the same reference.

Also, this error seems non-critical, so I am supposing the final error is unrelated?

Thank you!

-Christopher

**Comment by warrenmcg** [comment]
I think this is related to your previous issue (#175). Did you find out if the files were corrupted on the server filesystem?

**Comment by channsoden** [comment]
Thanks for your continued help!

I checked all my files, and there is no evidence of corruption other than the strange errors I'm getting. All of the different versions of the files seem identical. This error was also generated using a different set of Kallisto runs. I am using the same reference, but different samples from a separate sequencing experiment. These files were generated last Monday (the 21st) using kallisto 0.43.1.

**Comment by warrenmcg** [comment]
Hi @channsoden, this is perplexing to me. Could you post a link to a sample that gives this specific error rather than the one from #175?

Pinging @pimentel, any thoughts? Issue #175 has an example HDF5 file to play around with. I think these are better posted on kallisto’s issue board. Do you agree?

**Comment by channsoden** [comment]
Hmm, I am unable to recreate the error today. I am thinking maybe this was the result of some of the vestigal testing code that you had given me in #175 and I had left in my script. Now I am getting the same problems as in #175 . normalizing est_counts fails, likely because rhdf5::h5read return an object of entirely NULL values on these h5 files as well.

I tried reading in one of the h5 files using h5py and they look quite sane (definitely not null).

I am wondering if this isn't an issue with rhdf5, even? Looks like I'm using 2.22.0, and the most current is 2.24.0. I'll try updating that.

**Comment by channsoden** [comment]
Updating to rhdf5 2.25.3 has no change.

**Comment by pimentel** [comment]
Closing since a kallisto H5 issue. Continuing discussion at #175.
