### ISSUE TITLE
Typo in sleuth.R in line 832

### ISSUE THREAD

**Issue by pkerbs** [pachterlab/sleuth#181]
Hello,
while running sleuth_prep function this error appears:
```
Error in paste(dupliated_ids, collapse = ", ") : 
  object 'dupliated_ids' not found
```
Seems to be a typo (should be 'duplicated_ids') in the sleuth.R script

Best wishes,
Paul

**Comment by pimentel** [comment]
Ha, thanks. Oddly did not appear in testing. Will add to test data and fix bug shortly.

**Comment by warrenmcg** [comment]
Hi @pkerbs, thanks for the catch! @pimentel, I've pushed the typo fix to master. I'll also add in the extra testing bit.
