### ISSUE TITLE
Issue with sleuth install

### ISSUE THREAD

**Issue by Kappy2** [pachterlab/sleuth#225]
I am trying to install sleuth and seem to run into issues with installing the developer tools. It seems like something is missing. Please help! thanks.
I input: 
biocLite("devtools")

gives the following:

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.4 (2018-03-15).
Installing package(s) ‘devtools’
also installing the dependencies ‘xml2’, ‘roxygen2’, ‘rversions’

trying URL 'https://cloud.r-project.org/src/contrib/xml2_1.2.2.tar.gz'
Content type 'application/x-gzip' length 261081 bytes (254 KB)
==================================================
downloaded 254 KB

trying URL 'https://cloud.r-project.org/src/contrib/roxygen2_6.1.1.tar.gz'
Content type 'application/x-gzip' length 178346 bytes (174 KB)
==================================================
downloaded 174 KB

trying URL 'https://cloud.r-project.org/src/contrib/rversions_2.0.0.tar.gz'
Content type 'application/x-gzip' length 9722 bytes
==================================================
downloaded 9722 bytes

trying URL 'https://cloud.r-project.org/src/contrib/devtools_2.2.0.tar.gz'
Content type 'application/x-gzip' length 370794 bytes (362 KB)
==================================================
downloaded 362 KB

* installing *source* package ‘xml2’ ...
** package ‘xml2’ successfully unpacked and MD5 sums checked
Package libxml-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libxml-2.0' found
Package libxml-2.0 was not found in the pkg-config search path.
Perhaps you should add the directory containing `libxml-2.0.pc'
to the PKG_CONFIG_PATH environment variable
No package 'libxml-2.0' found
Using PKG_CFLAGS=
Using PKG_LIBS=-lxml2
------------------------- ANTICONF ERROR ---------------------------
Configuration failed because libxml-2.0 was not found. Try installing:
 * deb: libxml2-dev (Debian, Ubuntu, etc)
 * rpm: libxml2-devel (Fedora, CentOS, RHEL)
 * csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
--------------------------------------------------------------------
ERROR: configuration failed for package ‘xml2’
* removing ‘/home/kpoon/R/x86_64-pc-linux-gnu-library/3.4/xml2’
ERROR: dependency ‘xml2’ is not available for package ‘roxygen2’
* removing ‘/home/kpoon/R/x86_64-pc-linux-gnu-library/3.4/roxygen2’
ERROR: dependency ‘xml2’ is not available for package ‘rversions’
* removing ‘/home/kpoon/R/x86_64-pc-linux-gnu-library/3.4/rversions’
ERROR: dependencies ‘roxygen2’, ‘rversions’ are not available for package ‘devtools’
* removing ‘/home/kpoon/R/x86_64-pc-linux-gnu-library/3.4/devtools’

The downloaded source packages are in
	‘/tmp/Rtmp1wrGR9/downloaded_packages’
installation path not writeable, unable to update packages: boot, class,
  cluster, codetools, foreign, lattice, MASS, Matrix, mgcv, nlme, rpart,
  survival
Warning messages:
1: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘xml2’ had non-zero exit status
2: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘roxygen2’ had non-zero exit status
3: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘rversions’ had non-zero exit status
4: In install.packages(pkgs = doing, lib = lib, ...) :
  installation of package ‘devtools’ had non-zero exit status

**Comment by mschilli87** [comment]
@Kappy2: Which operating system are you on?

The relevant part of the error message is here:

```
Configuration failed because libxml-2.0 was not found. Try installing:
deb: libxml2-dev (Debian, Ubuntu, etc)
rpm: libxml2-devel (Fedora, CentOS, RHEL)
csw: libxml2_dev (Solaris)
If libxml-2.0 is already installed, check that 'pkg-config' is in your
PATH and PKG_CONFIG_PATH contains a libxml-2.0.pc file. If pkg-config
is unavailable you can set INCLUDE_DIR and LIB_DIR manually via:
R CMD INSTALL --configure-vars='INCLUDE_DIR=... LIB_DIR=...'
```

Did you try to follow these instructions already?
If so, where did it fail? If not, please do. :wink:

**Comment by Kappy2** [comment]
I'm using atmosphere, on Ubuntu Rstudio. 
I realized that this file is missing. I poked around on the GUI desktop version to see if I could find the file and I could not. I tried to install the libxml2, but received an error message that the xml2 is not there.
I am new to using command line, so I don't know if I am executing those commands correctly.

**Comment by mschilli87** [comment]
I don't know about atmosphere but on Ubuntu

```sh
sudo apt-get update && \
sudo apt-get install libxml2-dev
```

should do the trick.

**Comment by Kappy2** [comment]
That script gives me an error message. 
I start R, install biocLite rhdf5, then get stuck..

I am following the directions on this page:
https://pachterlab.github.io/sleuth/download

**Comment by mschilli87** [comment]
@Kappy2:  It would be much easier to help you if you would share the error message you get.
Note that the commands I gave you above are not R commands but have to be typed into the command line of your Ubuntu terminal. `sleuth` requires the R package `xml2` which in turn requires the system library `libxml-2.0` which on Ubuntu is provided by the software package `libxml2-dev`. The R error message you copied to your first post told you this much. I told you how to install that package on an Ubuntu system. If you get an error, please share what error at what point. And please try to at least google the error message and solve the problem yourself *before* asking for help. :wink:

**Comment by Kappy2** [comment]
Got it, thank you. Again, complete beginner with command line... learning as I go.

Received another error, tried googling and could not figure it out. I know the error means I have the incorrect path to GitHub, or my access is denied, not sure how to continue from here. Thanks in advance.
Input: biocLite("pachterlab/sleuth")

BioC_mirror: https://bioconductor.org
Using Bioconductor 3.6 (BiocInstaller 1.28.0), R 3.4.4 (2018-03-15).
Installing github package(s) ‘pachterlab/sleuth’
Error: Failed to install 'unknown package' from GitHub:
  Problem with the SSL CA cert (path? access rights?)

**Comment by mschilli87** [comment]
What is the output of

```sh
lsb_realease
```

and

```sh
dpkg --get-selections | grep curl
```

(both are Linux commands, not R commands)?

**Comment by Kappy2** [comment]
Command 'lsb_realease' not found, did you mean:

  command 'lsb_release' from deb lsb-release

Try: apt install <deb name>


and:

curl						install
libcurl3-gnutls:amd64				install
libcurl3-nss:amd64				install
libcurl4:amd64					install
libcurl4-nss-dev:amd64				install

**Comment by Kappy2** [comment]
Sorry, corrected the lab_release :
No LSB modules are available.

**Comment by mschilli87** [comment]
@Kappy2:

Can you try the following in R?

```r
install.packages("miniCRAN")
install.packages(miniCRAN::pkgDep("devtools"))
```

This will re-install the  `devtools` package (`devtools::install_github` is used internally by your `biocLite` call) and all its dependencies. My guess is there is something off with either you `curl` and/or `httr` installation. Also, make sure `BiocInstaller::biocValid()` returns `TRUE` on your system.

**Comment by Kappy2** [comment]
Could not connect via terminal so couldn't copy and paste correctly, but this is the message I get below:
BiocInstaller::biocValid() 

error in loadNamespace(name): there is no package called 'bioInstaller'

**Comment by Kappy2** [comment]
Just wanted to update you that I got it installed. Cyverse changed something on Ubuntu on their end... Thank you for the help!
