### ISSUE TITLE
plot_volcano: Object 'b' not found

### ISSUE THREAD

**Issue by umasstr** [pachterlab/sleuth#230]
I assume that this error means that plot_volcano cannot find my Wald beta values? I believe that I ran sleuth_wt successfully. Any help would be greatly appreciated:

**models(so)**
[  full  ]
formula:  ~condition 
data modeled:  obs_counts 
transform sync'ed:  TRUE 
coefficients:
	(Intercept)
 	conditionok186
[  reduced  ]
formula:  ~1 
data modeled:  obs_counts 
transform sync'ed:  TRUE 
coefficients:
	(Intercept)

**tests(so)**
~likelihood ratio tests:
	reduced:full
~wald tests:
	[ full ]
	conditionok186

**plot_volcano(so,"conditionok186",test_type = "wt")**
Error in FUN(X[[i]], ...) : object 'b' not found

**Comment by pimentel** [comment]
hm, it seems to not be pulling out the effect sizes from the `sleuth_results` table.

can you do me a favor?

```{r}
debugonce(plot_volcano)
plot_volcano(so,"conditionok186",test_type = "wt")
```
then hit enter until you get to the line that says:

```{r}
  res <- dplyr::mutate(res, significant = qval < sig_level)

```

then report back the result from:

```{r}
colnames(res)
```

**Comment by Rhinogradentia** [comment]
This seems to be the same  error as in #233 - there it is a missing parameter for sleuth_results.

**Comment by steachhr** [comment]
Hi, 

I'm getting the same 'object b not found' error while trying to generate volcano plots. I ran the code above, and the colnames(res) returns: 

[1] "target_id"                  "ext_gene"                  
[3] "num_aggregated_transcripts" "sum_mean_obs_counts"       
[5] "pval"                       "qval"

**Comment by umasstr** [comment]
Hi all, there may have been a problem with gene/tx aggregation in sleuth prep. I used an updated biomart ensembl host and my issue was resolved. Not sure if this is related, but hope it helps...

**Comment by ymatmt** [comment]
Hi, 
> I used an updated biomart ensembl host and my issue was resolved.
How do you do it? I got a same error.

**Comment by umasstr** [comment]
Hi ymatmt, 
I stopped using an old ensembl archive ("archive.dec2015...") in the mart variable, and instead use  host = "www.ensembl.org"). I'm not sure why this helped. I'd be happy to test out a couple of your abundance files if you'd like.

**Comment by ymatmt** [comment]
Finally it works! Thank you!
