### ISSUE TITLE
sleuth_results(so, 'conditionscramble') Error

### ISSUE THREAD

**Issue by jianwang2014** [pachterlab/sleuth#24]
Dear Sleuth developers:

The following error occurred after Sept 23 hotfix of cluster_hmap while running your example.

> results_table <- sleuth_results(so, 'conditionscramble')
 Hide Traceback
 
 Rerun with Debug
 Error in data.table::setkeyv(x, by$x) : 
  4 arguments passed to .Internal(nchar) which requires 3 
4 data.table::setkeyv(x, by$x) 
3 left_join.data.table(data.table::as.data.table(tids), data.table::as.data.table(res), 
    by = "target_id") 
2 dplyr::left_join(data.table::as.data.table(tids), data.table::as.data.table(res), 
    by = "target_id") at model.R#173
1 sleuth_results(so, "conditionscramble") 

Thanks,
Jian

**Comment by pimentel** [comment]
hi,

could you please provide your `sessionInfo()`?


thanks,

harold

**Comment by jianwang2014** [comment]
Hi, I would like to close this issue.  It turns out it is caused by the version of R 3.2.0 I am using.  Upgrading to R 3.2.1 or R 3.2.2 solved it.  
This following post explained it clearly.
http://stackoverflow.com/questions/31142280/unusual-error-in-setkeyv-with-data-table

Thanks much and I apologize,

-Jian
