### ISSUE TITLE
sleuth error on a single contig analysis

### ISSUE THREAD

**Issue by peterdfields** [pachterlab/sleuth#25]
Hi

I'm trying to apply kallisto and sleuth to a single, focal contig of interest. The contig is ~1Mb. I used kallisto to align 6 different samples, each an Illumina paired-end RNAseq dataset, three replicates of a control and treatment. kallisto seemed to run as expected, generated the expected files. I then tried to follow along with the sleuth tutorial and everything seemed fine up to:

> so <- sleuth_prep(kal_dirs, s2c, ~ condition)
reading in kallisto results
......
normalizing est_counts
1 targets passed the filter
Error in apply(mat, 1, function(row) !any(round(row) == 0)) : 
  dim(X) must have a positive length

Given that the sample dataset executes fine I assume something must be going wrong with my present dataset. Please let me know if additional info might be useful for understanding the observed error.

**Comment by pimentel** [comment]
Can you show us your s2c matrix?

Thanks,

Harold

On Friday, October 2, 2015, peterdfields <notifications@github.com> wrote:

> Hi
>
> I'm trying to apply kallisto and sleuth to a single, focal contig of
> interest. The contig is ~1Mb. I used kallisto to align 6 different samples,
> each an Illumina paired-end RNAseq dataset, three replicates of a control
> and treatment. kallisto seemed to run as expected, generated the expected
> files. I then tried to follow along with the sleuth tutorial and everything
> seemed fine up to:
>
> so <- sleuth_prep(kal_dirs, s2c, ~ condition)
> reading in kallisto results
> ......
> normalizing est_counts
> 1 targets passed the filter
> Error in apply(mat, 1, function(row) !any(round(row) == 0)) :
> dim(X) must have a positive length
>
> Given that the sample dataset executes fine I assume something must be
> going wrong with my present dataset. Please let me know if additional info
> might be useful for understanding the observed error.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pachterlab/sleuth/issues/25>.
>


-- 
Harold


Please excuse any errors in syntax or grammar. I probably wrote this email
using speech recognition.

**Comment by peterdfields** [comment]
sure! is this just an R print call to the s2c object? ie the matrix with sample, condition as columns, and then sample ID and treatment as rows. Or something else?

**Comment by pimentel** [comment]
yup! since you only have a few samples that shouldn't be too big. just type `print(s2c)` in the R console and paste output here. Thanks

**Comment by peterdfields** [comment]
The following is the output:

              sample condition
1 HS_CO_I_r1   control
2 HS_CO_I_r2   control
3 HS_CO_I_r3   control
4 HS_PA_I_r1  infected
5 HS_PA_I_r2  infected
6 HS_PA_I_r3  infected

**Comment by pimentel** [comment]
you only have 1 contig, so there's no way to do normalization. also, there is no way to do shrinkage estimation on this (the ability to do tests with very few samples comes from pooling the information together across transcripts). is there a reason that you are only including 1 contig?

**Comment by pimentel** [comment]
closing this issue because it's not really a use case for sleuth. feel free to continue asking questions here, though
