### ISSUE TITLE
sort by b or mean_obs? 

### ISSUE THREAD

**Issue by whiteorchid** [pachterlab/sleuth#264]
Dear guys,

May I know if you sort by **b** or **mean_obs**? Trying to sort to get the most variable genes. Thank you very much! :)

Best,

**Comment by mschilli87** [comment]
I think most people select on mean_obs and p. [This paper](https://doi.org/10.1093/bib/bbab053) suggests a more elaborate alternative: https://mebpr.shinyapps.io/activevp/
There is a similat tool implented in R for 'offline' use: https://pneuvial.github.io/sanssouci/

**Comment by whiteorchid** [comment]
Great! Thank you very much! :)

**Comment by mschilli87** [comment]
Glad if I could help.

PS: If this solved your question, consider closing this issue as the `sleuth` maintainers seem quite busy these days and having less issues for them to go through for them in the limited time they might have will allow them to focus on the most pressing issues more easily and thus eventually benefit everyone. 😉
