### ISSUE TITLE
create efficient sleuth storage and re-factor memory usage

### ISSUE THREAD

**Issue by pimentel** [pachterlab/sleuth#40]
currently, we load all of the bootstraps and keep them in memory. this is fine for small experiments, but quickly grows out of hand when the number of bootstraps is large and/or the number of experiments is large. the reason for keeping all of the bootstraps and memory is currently to make plotting and visualization simple. technically, all of the plots that we make can be made by simply storing the summary statistics. thus, we should (1) optimize the sleuth object so that we don't need to store everything, and (2) create a format, possibly in hdf5, that efficiently represents the sleuth object.

here is a very rough outline:

- [x] identify when and where to compute summary statistics and discard all of bootstraps. 1 possibility is to read in only the observations, compute normalization factors, then read in the bootstraps and normalize those reading in only 1 set of bootstraps at a time.
- [x] re-factor all of the plots and code that depends on the previous item
- [x] the code should not be so cumbersome that it does not allow us to do arbitrary transformations
- [ ] identify redundant data structures (a subset data frame with only filtered information) and do not store these in the binary format
- [ ] decide whether or not HDF5 is the best format for this -- it might be a pain to store the linear models in H5

the hope of this feature is to make sleuth significantly more memory efficient as well as being able to pass around sleuth objects to other scientist very easily

**Comment by psturmfels** [comment]
Sorry it's taken so long to respond. So is all of this initial bootstrap handling done in sleuth_prep() ?
Do we want to keep it that way/would sleuth_prep be the right place to calculate summary statistics? 

Also, sleuth_prep seems pretty difficult to understand. Any points on getting through it?

**Comment by pimentel** [comment]
Most of this stuff was addressed in #63 which is now merged into `devel`. We should add some functions:

```r
sleuth_save() 
sleuth_load()
```

For now, they will be simple calls to `saveRDS()` and `readRDS()`, but it will be nice to have these stubs if we decide to change the format in the future.

**Comment by pimentel** [comment]
More or less done. Good work, @psturmfels !

**Comment by slowkow** [comment]
I have 175 samples, 20,508 transcripts, human, 100 bootstraps.

All of the output files created by `kallisto` are just **8G**:

```bash
du -hs output/
8.0G    output/
```

The RDS object, on the other hand, is already over **23G** in size and still growing (hasn't finished writing yet). I'm saving the object like this:

```r
saveRDS(so, file = "so.rds")
```

- Does the `so` object hold multiple redundant copies of the same data?

- Could I ask if you have an estimate for how large the RDS file is expected to be relative to the kallisto output files? For example, will it be 100 times larger than the 8G kallisto output files?
If it is expected to be very large, then I won't bother saving it. It seems that saving and loading will be slower than re-running `sleuth_prep` for my data.

**Comment by pimentel** [comment]
Hi @slowkow which version of sleuth are you using? If you are using the version in `devel`, this is the 1 that has been optimized. The old version (and also `master`) have not been optimized yet and will result in very large files. Unfortunately, during development the 2 branches diverged very much and I will be merging them together this coming week. That is to say that if you are interested in gene aggregation, unfortunately the file sizes will be very large.

Regarding the optimized version, the RDS files should be a fraction of the kallisto output since it is simply storing summary statistics.

Keep an eye out for a new version sometime next week. If you are only interested in transfer level analysis, then please try installing the version from `devel`.

Thanks.

**Comment by slowkow** [comment]
Thanks for the quick reply! I used sleuth 0.28.1 and kallisto 0.43.0.

That makes sense. I'll definitely look out for the new version. For now, I'll continue without saving the RDS file. Good luck with the merge! Hope it goes smoothly.
