### ISSUE TITLE
More complex contrasts

### ISSUE THREAD

**Issue by roryk** [pachterlab/sleuth#54]
Hi Harold,

How do I do more complex contrasts with sleuth? For example with a design matrix:

```
         hm fooA fooB fooC
sampleA1  1    1    0    0
sampleA2  2    1    0    0
sampleA3  1    0    1    0
sampleB1  2    0    1    0
sampleB2  1    0    0    1
sampleB3  2    0    0    1
```

How do I look specifically at `fooC-fooB`, etc?

**Comment by pimentel** [comment]
@roryk currently contrasts of that type aren't supported (they will be in the next version). Depending on what you might be interested in, a nested model might help, in which case you can use `sleuth_lrt`

**Comment by roryk** [comment]
Thanks Harold, `sleuth_lrt` solves a bunch of our use cases.

**Comment by pimentel** [comment]
Cool. Glad to hear it. I'm hoping to have the next version ready in about 2 weeks.
