### ISSUE TITLE
Error when following the 'Introduction to sleuth' vignette 

### ISSUE THREAD

**Issue by tiagobrc** [pachterlab/sleuth#60]
When performing this command like in the picture, I get an error:

> so <- sleuth_prep(kal_dirs, s2c, ~ condition)
Error in sleuth_prep(kal_dirs, s2c, ~condition) : 
  'kal_dirs' (sample_to_covariates) must be a data.frame
>

![screenshot from 2016-01-25 19-05-33](https://cloud.githubusercontent.com/assets/12516337/12564540/e319bf2a-c396-11e5-8e12-a08b61620586.png)

What I am doing wrong?

**Comment by psturmfels** [comment]
Looks like you have a deprecated version of the intro page. The most recent version of sleuth does not accept the kallisto directories directly. Instead, your directories should appear in the 'sample_to_covariates' data frame in a column entitled "path"

See here for more info: https://github.com/pachterlab/sleuth/issues/46

**Comment by tiagobrc** [comment]
Thank you for your attention.
