### ISSUE TITLE
Error during sleuth_prep

### ISSUE THREAD

**Issue by ifiddes** [pachterlab/sleuth#72]
I got the following error during sleuth_prep:

`> so <- sleuth_prep(s2c, ~ condition)
reading in kallisto results
................................
normalizing est_counts
Error in utils::getS3method("as_data_frame", "matrix", envir = asNamespace("tibble")) : 
  unused argument (envir = asNamespace("tibble"))`

Full code up to this point, following the vignette:

`````` library('sleuth')

base_dir <- '/Users/ifiddes/hive/comparativeRNAseq/test_kallisto'
sample_id <- dir(file.path(base_dir,"results"))

kal_dirs <- sapply(sample_id, function(id) file.path(base_dir, "results", id))

s2c <- read.table(file.path(base_dir, 'conds.txt'), header=T, stringsAsFactors=F)
s2c <- dplyr::mutate(s2c, path = kal_dirs)
so <- sleuth_prep(s2c, ~ condition)```
``````

**Comment by ifiddes** [comment]
The error appears in the function `spread_abundance_by` on the first line, where the variable `var_spread` is assigned.

I think this may be a problem with my experiment - I am working on testing comparative gene annotation sets, and I am attempting to use differential testing tools as a way of diagnosing differences. This means that I am using the same RNAseq data with different annotations. I recognize this violates underlying assumptions about the model. I assume the problem is due to the effective length being different for the two conditions.

**Comment by warrenmcg** [comment]
Hi @ifiddes, following up on this issue, did updating tidyr as suggested in #77 fix the issue for you? If not, I would like to explore what about your given set up led to the error.

**Comment by warrenmcg** [comment]
pinging @ifiddes! Do you still have this issue after updating tidyr? We're clearing out issues before the next stable release.

**Comment by ifiddes** [comment]
I honestly cannot remember at this point, and am probably unable to
reproduce this problem. Please close this, sorry!

Ian Fiddes, PhD

**Comment by warrenmcg** [comment]
Ok, feel free to re-open if this problem arises again! Happy Analyzing! :)
