### ISSUE TITLE
Error in utils::getS3method("as_data_frame", "matrix", envir = asNamespace("tibble")

### ISSUE THREAD

**Issue by hjeanc** [pachterlab/sleuth#77]
Someone has already brought up this issue "Error during sleuth_prep
#72 opened 23 days ago by fiddles" but there is no response that I can see. I was able to run Sleuth with no problem and suddenly this same issue came up. Please see this similar discussion [as_data_frame_matrix: "envir" argument in getS3method](https://github.com/hadley/tidyr/issues/202)

I have attempted to work around this for weeks and all of my progress is halted. Can you please address this issue?

```
> t2g <- read.table('/oasis/tscc/scratch/hjclemons/kallisto/case_sleuth/t2g.txt', sep = '\t', header = TRUE)
> s2c <- read.table('/oasis/tscc/scratch/hjclemons/kallisto/case_sleuth/UMB4337_vs_B5666.txt', sep = '\t', header = TRUE)
> so <- sleuth_prep(s2c, ~ condition, target_mapping = t2g)
reading in kallisto results
.........................
normalizing est_counts
Error in utils::getS3method("as_data_frame", "matrix", envir = asNamespace("tibble")) : 
  unused argument (envir = asNamespace("tibble"))
```

**Comment by pimentel** [comment]
@hjeanc sorry about that. I have been on medical leave and am slowly making my way back to progress. anyway, I will try to have this fixed within the next week, however, it seems that it has been fixed already on the tidyr master branch. Have you tried installing the development version from GitHub?

If not, try following:

```
# install.packages("devtools")
devtools::install_github("hadley/tidyr")
```

**Comment by hjeanc** [comment]
Hi I hope you are feeling better. So that actually worked perfectly! I could tell from the conversation that they were submitting a fix but, being relatively new to computing stuff, I did not know how to access it. Thanks!

**Comment by warrenmcg** [comment]
Hi @hjeanc, since the suggested tidyr fix worked for you, I'm going to close this issue. If it comes up again, please feel free to reopen this issue. Thanks!
