### ISSUE TITLE
Memory usage on large (~200) cohort

### ISSUE THREAD

**Issue by chrisamiller** [pachterlab/sleuth#85]
When run on a large cohort of about 200 samples, sleuth consumes massive amounts of memory. Using default settings, I wasn't able to get it to run, even on a box with 96GB of RAM. By setting "max_bootstrap = 30", I was able to get results, but it still consumed greater than 40GB.  

I have some even larger cohorts I'd like to analyze - are there plans to reduce the memory usage? Thanks!

**Comment by pimentel** [comment]
Hi @chrisamiller thanks for the comment. Indeed, we have implemented it in the development version (see branch `devel`). However, it needs to be merged into the main branch which has diverged and includes gene aggregation. Currently, the development branch does not support gene aggregation. This is high on my priority list and will hopefully get done by the end of this week. If you are only interested in isoform level analysis, the development branch should be sufficient.


Thanks,

Harold

**Comment by chrisamiller** [comment]
Great, I'll look for that release soon - thanks!

**Comment by jashephe** [comment]
Hi, just wanted to check in to see if there's been any progress on merging in the memory reduction improvements. I've run into the same problem that Chris describes, with a group of just under 200 samples. Memory usage seems to exceed 256 GB, even when limiting to 25 bootstraps. Thanks!

**Comment by pimentel** [comment]
Ah. I've been super lagging on this. This will certainly get done at the latest, early next week. Really sorry about this...

**Comment by roryk** [comment]
Thanks Harold. Sleuth is awesome and having it runnable on larger samples would be awesome. hope you are feeling better.

**Comment by jashephe** [comment]
Yeah, thanks for all the hard work!

**Comment by pimentel** [comment]
I realize this is several months late but the latest version has all of the modifications I mentioned and several others.

Let us know if you use it and if it works (ha!).


Best,

Harold
