### ISSUE TITLE
sleuth VS DESeq2

### ISSUE THREAD

**Issue by jcgrenier** [pachterlab/sleuth#88]
Hello there,

First of all, I know we can directly compare both approaches, I'm just wondering how to get results regarding different covariates in the same way that DESeq2 could do.

Here's an example of what I'm doing on DESeq2 and what I did on sleuth to be able to get the same kind of thing. 

`#DESeq2 :
dds <- DESeqDataSetFromTximport(txi, sampleTable, ~Gender+Age+PMI+PH+RIN+Group)
dds <- DESeq(dds)
res <- results(dds)

#Here I'm adding the pvalues and the log2FoldChange for that covariate to my present table.
res$Age = results(dds,names="Age")$pvalue
res$Age_l2fc = results(dds,names="Age")$log2FoldChange

#sleuth :
so_full <- sleuth_prep(s2c, ~ Group + Gender + Age + PMI + PH + RIN)
so_full <- sleuth_fit(so_full)
so <- sleuth_wt(so_full, 'GroupSA' , which_model = "full")
results_table <- sleuth_results(so,'GroupSA')

#Applying for age now.
so <- sleuth_wt(so_full, 'Age' , which_model = "full")
results_table <- sleuth_results(so,'Age')`

So, is this procedure equivalent or should I do something different?

Thanks a lot for your help, it's really appreciated.

JC

**Comment by jcgrenier** [comment]
Hello there,

Just a quick follow up. Did you see the post? 
Thanks for your help!!

**Comment by warrenmcg** [comment]
Hi @jcgrenier,

These are equivalent, in that sense that you are focusing on just one covariate from the model (either `Group` or `Age`). As long as you keep in mind the other differences (how each does their respective filtering and statistics), you should be able to compare the results you get from the code you've posted here.

Also, here's a tip: if you want to show code, you can either click the "insert code" button at the top of the comment box, or you can use the "grave accent" mark ("``", top left of your keyboard) to mark off code like `this` or 
```
this
```
more information can be found here: https://help.github.com/articles/creating-and-highlighting-code-blocks/

**Comment by jcgrenier** [comment]
Thanks @warrenmcg.

I've updated the code part on my previous post. Thanks for the tip!

**Comment by warrenmcg** [comment]
Glad to help! FYI, it didn't work. If the code is a small part of a paragraph, you enclose it using one mark on each side (I'll use single quotes to demonstrate, but you would use the `` marks): like 'this' to produce `this`.

If you want to enclose a larger block, you use three marks above and below the code.

Like this:
'''
example code line 1
example code line 2
'''

to get this:
```
example code line 1
example code line 2
```

**Comment by jcgrenier** [comment]
Now it should be ok! :)
