### ISSUE TITLE
Simplified installation instructions

### ISSUE THREAD

**Issue by mtmorgan** [pachterlab/sleuth#9]
`biocLite()` knows how to install github packages (with devtools), so

    source("http://bioconductor.org/biocLite.R")
    biocLite("devtools")    # only if devtools not yet installed
    biocLite("pachterlab/sleuth")

will install sleuth and all dependencies, including rhdf5. An alternative formulation is

    source("http://bioconductor.org/biocLite.R")
    options(repos=biocinstallRepos())
    install_github("pachterlab/sleuth")

**Comment by pimentel** [comment]
Wonderful suggestion. I've updated the README. I'll update the vignette as soon as I get a chance fixing some bug reports via email :)


Thanks!

Harold
